// Generated by https://quicktype.io

export interface RegisterModel {
	email: string;
	password: string;
	confirmPassword: string;
	firstName: string;
	lastName: string;
	profileImageUrl: string;
}


// Generated by https://quicktype.io

export interface RegisterResponseModel {
  canLogin: boolean;
}
