import { IUser } from './../models/IUserModel';

export interface SignInModel {
	email: string;
	password: string;
}

// Generated by https://quicktype.io

export interface SiginResponseModel {
	id: string;
	auth_token: string;
	expires_in: number;
	roles: any[];
	user: IUser;
}
